# Generated by Django 4.2.13 on 2026-10-01 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_groupuser_group_id_alter_groupuser_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=64, unique=True)),
                ('state', models.BinaryField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='GroupUser',
        ),
    ]
