# Generated by Django 4.2.13 on 2026-10-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_roomdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomdocument',
            name='compressed',
            field=models.BooleanField(default=False),
        ),
    ]
